### ISSUE TITLE
[BE] Member 엔티티 추가 및 MemberAction 삭제

### ISSUE THREAD

**Issue by Arachneee** [woowacourse-teams/2024-haeng-dong#546]
## 📄 설명

String 컬럼으로 관리하던 Member를 테이블로 분리하고 MembeAction을 삭제합니다.

## 🏁 할 일

- [ ] Member 엔티티 추가
- [ ] MemberAction 삭제
- [ ] API 변경

### 테이블 분리 이유
- 테이블에 Member의 이름이 중복된 데이터가 많이 발생
- 이름 변경시 해당하는 모든 칼럼의 이름을 변경해야하는 문제 발생

### 엔티티 변경 사항
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/8d69dad7-95d7-4f91-b281-d7b8defdc181">

- Member를 event와 name으로 생성하게 하여 memberAction은  Member와의 연관관계만 가질 수 있도록 변경합니다.
- BillActionDetail도 Member을 참조하도록 변경합니다.

### API 변경 사항
Member name의 String 값 대신 id를 주고 받을 수 있도록 API 엔드포인트 및 Request, Response 형태 변경이 필요합니다.

**Comment by Todari** [comment]
status todo로 옮겨놓을게요~
