### ISSUE TITLE
[BE] Domain 패키지와 Exception 패키지간의 순환 참조

### ISSUE THREAD

**Issue by Arachneee** [woowacourse-teams/2024-haeng-dong#580]
## 📄 설명

예외 메시지 구체화를 위해 HaengdongErrorCode에서 Domain 패키지를 참조하고 Domain에서는 검증을 위해 Exception 패키지를 참조하는 순환 참조 문제가 있습니다.

![image](https://github.com/user-attachments/assets/8489e2b4-b8cd-4337-87cb-3e6caf8cd8b4)

## 🏁 할 일

- [x] 예외 메시지 전달 방식을 변경합니다.

**Comment by Todari** [comment]
status todo로 옮겨놓을게요~
