### ISSUE TITLE
[BE] 행사 멤버 추가 시 500 에러 발생

### ISSUE THREAD

**Issue by khabh** [woowacourse-teams/2024-haeng-dong#588]
## 📄 버그 내용 
어떤 버그인지 간결하게 설명해주세요.
![image](https://github.com/user-attachments/assets/3b5f7f39-6340-4ac4-babb-58d9d2d95bb1)

## 🚨 버그 발생 상황
서버로 멤버 추가 api를 호출할 시에 500 에러가 발생한다.
<img width="1093" alt="image" src="https://github.com/user-attachments/assets/1005a833-b5bb-4a20-a900-6aca89dfd693">

**Comment by Todari** [comment]
status todo로 옮겨놓을게요~
