### ISSUE TITLE
[BE] 데이터베이스 Replication 구성에 따른 Read / Write 분리하기

### ISSUE THREAD

**Issue by khabh** [woowacourse-teams/2024-haeng-dong#590]
## 📄 설명
데이터베이스 Replication 구성에 따라 Read / Write를 분리한다.

## 🏁 할 일
- [x] 데이터베이스 Replication 구성에 따라 Read / Write를 분리한다.
  - [x] application.yml 수정하기

**Comment by Todari** [comment]
status 설정 안돼있어서 Todo로 바꿔놓을게요~
