### ISSUE TITLE
[FE] 행사 이름 한글이 두 자 씩 입력되는 버그

### ISSUE THREAD

**Issue by jinhokim98** [woowacourse-teams/2024-haeng-dong#601]
## 📄 버그 내용 
행사 이름 한글 두 자 씩 입력되는 버그 발생

https://github.com/user-attachments/assets/31588e8c-3a44-481e-a587-eb4b2040bfad

**Comment by Todari** [comment]
@soi-ha 어제 웨디가 저한테 넘겨준 이슈인데, 내용은 오늘 정한 새로운 방식으로 소하가 다시 작성해도 좋아요~
