### ISSUE TITLE
[FE] 이벤트 페이지 TopNav 마진 문제

### ISSUE THREAD

**Issue by jinhokim98** [woowacourse-teams/2024-haeng-dong#673]
## 📄 버그 내용 
이벤트 페이지의 TopNav 부분 마진이 맞지 않습니다.
정산 초대하기 버튼 마진이 맞지 않아요

## 🚨 버그 발생 상황
![Image](https://github.com/user-attachments/assets/b0f4f73c-5002-41f3-a298-7686c86b9d48)

**Comment by Todari** [comment]
#681 과 함께 close  할게요~
