### ISSUE TITLE
[FE] 랜딩페이지 변경된 UI에 맞게 수정하기

### ISSUE THREAD

**Issue by soi-ha** [woowacourse-teams/2024-haeng-dong#685]
## 📄 설명

현재 랜딩페이지에 존재하는 서비스 이미지는 이전 UI로 되어있습니다.
UI가 변경되었기 때문에 랜딩페이지의 서비스 이미지를 변경해야 합니다.

## 🏁 할 일

- [ ] 서비스 이미지 변경하기

**Comment by Todari** [comment]
#760 에서 구현되어 close 하겠습니다
