### ISSUE TITLE
[FE] 성능개선 : [Largest Contentful Paint element]

### ISSUE THREAD

**Issue by jinhokim98** [woowacourse-teams/2024-haeng-dong#755]
## 📄 설명

랜딩 페이지와 관리자 페이지에서 발생하는 LCP 시간을 개선합니다.

## 🏁 할 일

- [ ] 랜딩 페이지 LCP 개선
- [ ] 관리자 페이지 LCP 개선

**Comment by Todari** [comment]
#774 
#776 
에서 해결된 issue라 close 하겠습니다~
